sonar.projectKey=mundial-2026-simulator
sonar.projectName=Mundial 2026 - Simulator API
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=static/**,tests/**,docs/**,*.md,demo_playwright.py
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
